### ISSUE TITLE
Missing dependency ntlm-client

### ISSUE THREAD

**Issue by tsuriga** [nmarus/node-ews#146]
Ntlm-client was introduced in pull request #79 but commit b9a16123e49913c467b6103e7a1d45c386e8c482 on the same day removed ntlm-client from package.json in master to master merge. Files lib/auth/ntlm.js and lib/auth/ntlm/http.js both attempt to require the package so I'm guessing the removal during merge was accidental and the dependency should still be present?

**Comment by timothy-tsang** [comment]
Hey @tsuriga , I'm having the same issues as you! I'm getting the error
`Cannot find module 'ntlm-client'` and I also believe this occurred when the new PR was committed.

**Comment by timothy-tsang** [comment]
Note: basically I believe the author made a mistake when he pushed to Master. I do see his PR 8 days ago, but I also see 2 merges to Master with no PR. The history seems a bit messed up.

Solution: just set my package.json to hold at 3.4.2 (remove ^ or ~). It solved the issue temporarily.

Hoping for a solution in the next upcoming days.

**Comment by tsuriga** [comment]
Since the project is not actively maintained anymore I don't know if there's going to be a resolution. If you wanted the latest changes you could also set the node-ews version to the exact 3.5.0 that has this issue and then declare ntlm-client as a dependency in your own package.json.  It's not really the purest way but it is a way.

Disclaimer: I didn't test the functionality, I just know it gets rid of the error.
